version: '3.9'

services:
  portfolio-db:
    image: postgres
    container_name: portfolio
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
