name: CI

on:
  push:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.1
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Audit
        run: pnpm audit
      - name: Unit Tests
        run: pnpm test:unit
